### ISSUE TITLE
Suggestion for Module-0 Slide 2 Japanese translation

### ISSUE THREAD

**Issue by nobuoimada** [KoukiHama/FOSSologySlides#1]
Hands-onスライドの日本語訳に対する変更提案です。個別に採否を決定できるよう、提案ごとにIssueを分けます。

Module-0, Slide 2
"What is the need today" は、後に続くスライドの内容から考えて、本日のトレーニングに必要なことではなく、今日のOSSコンプライアンスに求められていること、という意図ではないかと推察します。なので、「本日必要なこと」→「今日求められていること」に変更を提案します。

**Comment by KoukiHama** [comment]
「本日必要なこと」→「今日求められていること」に変更しました

**Comment by nobuoimada** [comment]
変更を確認したのでcloseします。
