### ISSUE TITLE
Module-A, Slide 16 (2)

### ISSUE THREAD

**Issue by nobuoimada** [KoukiHama/FOSSologySlides#11]
new licenses, rare licenses, licenses written for the US law, used in Europe, etc.

「新しいライセンス、珍しいライセンス、米国の法律に準拠して書かれたライセンスを欧州で使う場合など」を提案します。

**Comment by KoukiHama** [comment]
「新しいライセンス、珍しいライセンス、米国の法律に準拠して書かれたライセンスを欧州で使う場合など」に変更します．

**Comment by nobuoimada** [comment]
変更を確認したのでcloseします。
