### ISSUE TITLE
Module-B, Slide 4, homogeneous licensing

### ISSUE THREAD

**Issue by nobuoimada** [KoukiHama/FOSSologySlides#12]
(Apache projects are known for homogeneous licensing) の訳についてです。
直訳しにくいのでちょっと説明的になりますが、以下はどうでしょうか。

Apache プロジェクトは、Apache ライセンスと両立可能なライセンスのコードのみを受け入れることによって、プロジェクト全体を Apache ライセンスで一様にライセンス許諾していることで有名です。

**Comment by KoukiHama** [comment]
原文を注釈として含めたうえで，上記［Apache プロジェクトは、Apache ライセンスと両立可能なライセンスのコードのみを受け入れることによって、プロジェクト全体を Apache ライセンスで一様にライセンス許諾していることで有］に変更しました．

**Comment by nobuoimada** [comment]
変更を確認したのでcloseします。
