### ISSUE TITLE
Module-B, Slide 7 (1)

### ISSUE THREAD

**Issue by nobuoimada** [KoukiHama/FOSSologySlides#13]
「ソフトウェアコンポーネントのライセンスとコピーライトを追従するウェブサーバーアプリケーション」の「追従する」は少しわかりにくいと思います。また、copyrightの訳として、著作権、コピーライト、Copyrightsなどが混在しています。これらは、「著作権」に統一するのがわかりやすいかと思います。以下の訳文を提案します。

「ソフトウェアコンポーネントのライセンスと著作権のコンプライアンスのためのウェブサーバーアプリケーション」

「コピーライト」は、左のテキストボックスの中にもあります。

**Comment by KoukiHama** [comment]
［copyrightの訳として、著作権、コピーライト、Copyrightsが混在］
気づいていたのですがすっかり直すの忘れてました．ご指摘ありがとうございます。

まず，全体的に「著作権」に統一します．

「ソフトウェアコンポーネントのライセンスと著作権のコンプライアンスのためのウェブサーバーアプリケーション」を採用します．

**Comment by nobuoimada** [comment]
変更を確認したのでcloseします。
