### ISSUE TITLE
Module-B, Slide 7 (2), interfaces

### ISSUE THREAD

**Issue by nobuoimada** [KoukiHama/FOSSologySlides#14]
Web server based and command line interfaces
これは、WebペースとCLIベースの二つのインタフェースが用意されていることを意味していると思います。(interfaces が複数形なので)
「Webベースおよびコマンドラインベースのインターフェイスを実装」
を提案します。

**Comment by KoukiHama** [comment]
「Webベースおよびコマンドラインベースのインターフェイスを実装」を採用します

**Comment by nobuoimada** [comment]
変更を確認したのでcloseします。
