### ISSUE TITLE
Module-B, Slides 8 and 10, How does FOSSology work?

### ISSUE THREAD

**Issue by nobuoimada** [KoukiHama/FOSSologySlides#15]
スライドの表題は原文に忠実に訳すと「Fossologyはどう動くか？」だと思います。あるいは、スライドの内容に合わせて意訳して「FOSSologyを使った作業の流れ」などとする手もあると思います。

**Comment by KoukiHama** [comment]
8，10ともに「FOSSologyを使った作業の流れ」を採用します．

**Comment by nobuoimada** [comment]
変更を確認したのでcloseします。
