### ISSUE TITLE
Module-B, Slides 9 (2), Review copyright statements and correct in case

### ISSUE THREAD

**Issue by nobuoimada** [KoukiHama/FOSSologySlides#17]
右側のテキストボックスの中の、Review copyright statements and correct in case の訳ですが、「著作権のステートメントをレビューし、必要なら修正を行う」を提案します。

**Comment by KoukiHama** [comment]
「著作権のステートメントをレビューし、必要なら修正を行う」を採用します．

**Comment by nobuoimada** [comment]
変更を確認したのでcloseします。
