### ISSUE TITLE
Module-B, Slides 9 (3), Select the pop-up menu of the ionicons upload

### ISSUE THREAD

**Issue by nobuoimada** [KoukiHama/FOSSologySlides#18]
右側のテキストボックスの一番下、「ポップアップメニューを選択、ioniconsアップロード」ですが、ここは、左側のテキストボックスの "8. Generate desired report output" に対応した操作だと思います。なので、
「ionicons-3.0.0 アップロードの -- select action -- メニューから "Export ～" のいずれかを選択してレポートを生成」
のように書くと分かりやすいかと思います。

**Comment by KoukiHama** [comment]
「ionicons-3.0.0 アップロードの -- select action -- メニューから "Export ～" のいずれかを選択してレポートを生成」採用します．この書き方だと親切ですね．

**Comment by nobuoimada** [comment]
変更を確認したのでcloseします。
