### ISSUE TITLE
Module-B, Slide 9 (4) Select "go to all …. with licenses"

### ISSUE THREAD

**Issue by nobuoimada** [KoukiHama/FOSSologySlides#19]
右側のテキストボックスの中の、
・"go to all …. with licenses" を選択
・ライセンスレビューと決定を適用
ですが、go to ～ は実機では Go through all files with licenses になっています。また、「ライセンスレビューと決定を適用」も実際の操作に合わせて表記したほうがわかりやすいと思います。以下を提案します。

・"Go through all files with licenses" を選択
・ライセンスをレビューし、"Clearing decision type" のいずれかを選択してから "Submit" ボタンを押して判定結果を適用

**Comment by KoukiHama** [comment]
> 実際の操作に合わせて表記したほうがわかりやすいと思います。

同意です．以下を採用します．

・"Go through all files with licenses" を選択
・ライセンスをレビューし、"Clearing decision type" のいずれかを選択してから "Submit" ボタンを押して判定結果を適用

ここは本家の方にもなんらかの対応を報告しておきます．

**Comment by nobuoimada** [comment]
変更を確認したのでcloseします。
