### ISSUE TITLE
Module-0, Slide 3

### ISSUE THREAD

**Issue by nobuoimada** [KoukiHama/FOSSologySlides#2]
Check that everyone has been able to install on machine and download example files.

以前受講した際、インストールとサンプルファイルのダウンロードは、受講者があらかじめ各自実施したノートPCを持参することになっていました。元の英文も has been able to ... ですので、以下のように変更を提案します。

「全員が各自のマシンにインストールでき、サンプルファイルをダウンロードできていることの確認」

**Comment by KoukiHama** [comment]
全員が各自のマシンにインストールでき、サンプルファイルをダウンロードできていることの確認

に変更しました

**Comment by nobuoimada** [comment]
変更を確認したのでcloseします。
