### ISSUE TITLE
Module-B, Slide 9 (5) Select the copyright, e-mail, url

### ISSUE THREAD

**Issue by nobuoimada** [KoukiHama/FOSSologySlides#20]
「黄色のメニューバーエリアからthe copyright, e-mail, url section 選択」ですが、実際の画面に合わせて、「黄色のメニューバーエリアから Copyright/Email/Url/Author をクリック」を提案します。

**Comment by KoukiHama** [comment]
「黄色のメニューバーエリアから Copyright/Email/Url/Author をクリック」を採用します．

**Comment by nobuoimada** [comment]
変更を確認したのでcloseします。
