### ISSUE TITLE
Module-B, Slide 11, A Web server application for ...

### ISSUE THREAD

**Issue by nobuoimada** [KoukiHama/FOSSologySlides#21]
Issue #13 Module-B, Slide 7と同じです。以下の訳文を提案します。

「ソフトウェアコンポーネントのライセンスと著作権のコンプライアンスのためのウェブサーバーアプリケーション」

**Comment by KoukiHama** [comment]
「ソフトウェアコンポーネントのライセンスと著作権のコンプライアンスのためのウェブサーバーアプリケーション」を採用します．

**Comment by nobuoimada** [comment]
変更を確認したのでcloseします。
