### ISSUE TITLE
Modules B and D - The aggregated view

### ISSUE THREAD

**Issue by nobuoimada** [KoukiHama/FOSSologySlides#24]
Aggregated view という表現が、以下のスライドに出現しています。(見落としがあったらすみません)

Mod B, S 9 左
Mod D, S 5 左、右
Mod D, S 9 左
Mod D, S 13 左
Mod D, S 16 左
Mod D, S 20 左
Mod D, S 36 左、右

Aggregated view とは、Module B のスライド5, 6の挿絵のような、パッケージ全体を集約して表示するビューのことのようです。訳を統一したほうがよいと思います。何に統一するかですが、個人的には、いずれにせよGUIは英語なので「集約ビュー」などと訳するよりも原語のままのにしておいて、講師が口頭で補足するのが、すっきりするように思います。マイケルさんと会話するときもそのままで行けますし。どうしますか？

たとえば、Module B, Slide 9 の 4. Review the found licenses in the aggregated view だと、
案1：Aggregated viewで、検出されたライセンスをレビュー
案2：集約ビューで、検出されたライセンスをレビュー
などです。

**Comment by KoukiHama** [comment]
すべてAggregated viewにします．無理に訳す必要は確かになさそうです．

Mod D, S 16 左に関しては
At aggregated license browser view select link [edit] を

At aggregated license browser viewから [Edit]リンク選択

としています．

**Comment by nobuoimada** [comment]
変更を確認したのでcloseします。
