### ISSUE TITLE
Module-D, Slide 5 Example

### ISSUE THREAD

**Issue by nobuoimada** [KoukiHama/FOSSologySlides#25]
このスライドは、右側のテキストボックスの原文の意図が一部よくわからなかったのですが、左側のテキストボックスと対比させて考えると少しずつわかってきました。以下の流れのように思われます。

Upload an example file, jakarta-oro-2.0.7
例題のjakarta-oro-2.0.7をアップロードしてください。

Select the options in the upload menu
アップロードの際に、アップロードメニューのオプションを選択してください。(左側の2.に対応)

Go to browse and review the UI there
ブラウズ画面からアップロード名をクリックしてライセンスブラウザ画面に行き、そこのUIを再確認してください。(＝aggregated view)

Select licenses from drop-down menu at upload
ブラウズ画面の -- select action -- メニューから "Licenses" を選択してください。(＝single file view)

See the aggregated views and single file view: create decisions
ほらね、aggregated view と single file view があるでしょ。
では、ライセンスを決定して Submit してください。

First use of the bulk
バルク機能の初利用

Go to copyrights and correct found matches
Copyright のリンクへ行き、検出結果を修正してください。

ECC will be the same
ECCも同様

Select SPDX output from drop-down
ブラウズ画面の -- select action -- ドロップダウンからSPDXの出力形式を選択

以上から、右側のテキストボックスについて以下の訳を提案します。

・サンプルファイルのjakarta-oro-2.0.7をアップロード
・アップロードの際にアップロードのオプションを選択
・ブラウズ画面からアップロード名をクリックしてライセンスブラウザ画面に行き、そこのUIを再確認 (aggregated view)
・ブラウズ画面の -- select action -- メニューから "Licenses" を選択 (single file view)
・ライセンスを決定して結果を適用 (Submit)
・バルク機能の初利用
・Copyright のリンクへ行き、検出結果を修正
・ECCも同様
・ブラウズ画面の -- select action -- ドロップダウンからSPDXの出力形式を選択

ちょっとくどいですかね。

**Comment by KoukiHama** [comment]
> ちょっとくどいですかね。

これを使って説明することを考えると，くどいということはないと思います．


・サンプルファイルのjakarta-oro-2.0.7をアップロード
・アップロードの際にアップロードのオプションを選択
・ブラウズ画面からアップロード名をクリックしてライセンスブラウザ画面に行き、そこのUIを再確認 (aggregated view)
・ブラウズ画面の -- select action -- メニューから "Licenses" を選択 (single file view)
・ライセンスを決定して結果を適用 (Submit)
・バルク機能の初利用
・Copyright のリンクへ行き、検出結果を修正
・ECCも同様
・ブラウズ画面の -- select action -- ドロップダウンからSPDXの出力形式を選択

を採用します．ただ，こちらは原文のほうも修正があるべきかと思います．もしよろしければ，こちらに関しては　@nobuoimada さんの訳のような補足を加えるべきではないかとhttps://github.com/fossology/FOSSologySlides のissueにあげていただけませんか？（私が提案してもよいのですが．）

**Comment by nobuoimada** [comment]
原文のほうは、このままでまあいいかなと思います。変更を確認したのでcloseします。
