### ISSUE TITLE
Module-D, Slides 6-10 Bulk Scan

### ISSUE THREAD

**Issue by nobuoimada** [KoukiHama/FOSSologySlides#26]
スライド6から10にかけて、Bulk Scanの訳が、バルクスキャン、一括スキャン、一括検索などがあり、統一されていません。個人的には「バルクスキャン」が好みですが、どうしますか？

**Comment by KoukiHama** [comment]
全スライド［バルクスキャン］で統一しました．バルクという言葉は一般的にカタカナで使って問題ないと私も思います．

**Comment by nobuoimada** [comment]
変更を確認したのでcloseします。
