### ISSUE TITLE
Module-D, Slide 9 (1) Use bulk scan to accelerate it

### ISSUE THREAD

**Issue by nobuoimada** [KoukiHama/FOSSologySlides#27]
左側のテキストボックスの、2. Use bulk scan to accelerate it の下の最初の二つの箇条書きですが、「バルクスキャン用のフレーズは、別のアップロード(別のソフトウェアパッケージ)から持ってくるよりも同じアップロードの中から持ってくるほうが安全だ(誤検出の心配が少ない)」ということを言っているのだと思います。以下の訳を提案します。

Within an upload: select the text phrase
・そのアップロードの中から、テキストフレーズを選択する

Assumption: using text phrases within an upload appears safe
・仮定：同じアップロードの中のテキストフレーズを使うのが安全だろう

**Comment by KoukiHama** [comment]
Within an upload: select the text phrase
・そのアップロードの中から、テキストフレーズを選択する

Assumption: using text phrases within an upload appears safe
・仮定：同じアップロードの中のテキストフレーズを使うのが安全だろう

にそれぞれ変更しました．

**Comment by nobuoimada** [comment]
変更を確認したのでcloseします。
