### ISSUE TITLE
Module-D, Slide 9 (2) 3. More edits on files at once

### ISSUE THREAD

**Issue by nobuoimada** [KoukiHama/FOSSologySlides#28]
左側のテキストボックスの、3. More edits on files at once の下の

- Edit and bulk from aggregated view
- Edit is for irrelevant

ですが、ここの Edit は、スライド15～16で取り扱っている Edit 機能のことを言っているのだと思います。なぜなら、右側のテキストボックスに、「Zlibパッケージのcontribディレクトリ配下のBSLのケース」と書かれているからです。このケースでは、contrib配下のファイルすべてについてスキャンでBSL-1.0が検出されているので、この場合はBulk ScanではなくEdit機能を使って一括して決定するというもう一つの手がある、ということを言っているように思います。そこで、以下の訳を提案します。

左側の 3. More edits on files at once の部分

3. 複数のファイルを一度に編集するもう一つの方法
・Aggregated viewからの Edit およびバルクスキャン
・Editは、無関係な検出結果の除去にも

右側の Again の部分

さらに
・もう一つの例として、Zlibのcontrib配下のBSLのケース

**Comment by KoukiHama** [comment]
>この場合はBulk ScanではなくEdit機能を使って一括して決定するというもう一つの手がある、ということを言っているように思います。

確認したところ，上記で正解だと思います．

左側の 3. More edits on files at once の部分

複数のファイルを一度に編集するもう一つの方法
・Aggregated viewからの Edit およびバルクスキャン
・Editは、無関係な検出結果の除去にも
右側の Again の部分

・もう一つの例として、Zlibのcontrib配下のBSLのケース

に変更

**Comment by nobuoimada** [comment]
変更を確認したのでcloseします。
