### ISSUE TITLE
Module-D, Slide 9 (3) Zlib-possibility

### ISSUE THREAD

**Issue by nobuoimada** [KoukiHama/FOSSologySlides#29]
Zlib-possibility は、スキャンによる検出結果の一つなので、zlib候補と訳すよりもそのままのほうがわかりやすいと思います。

(some zlib-possibility)
・(Zlib-possibility と検出されたファイルがいくつかある)

Select zlib, remove zlib possibility, go next
・Zlibを選択し、Zlib-possibilityを削除して、次のファイルへ

**Comment by KoukiHama** [comment]
(some zlib-possibility)
・(Zlib-possibility と検出されたファイルがいくつかある)

Select zlib, remove zlib possibility, go next
・Zlibを選択し、Zlib-possibilityを削除して、次のファイルへ

に変更しました．

**Comment by nobuoimada** [comment]
右側のテキストボックスの二つ目の項目に、まだ Zlib-possibility がありました。私の指摘漏れです。すみません。

もう一つのファイルへ
・Zlib-possibility を選択
・バルクスキャンの定義：Zlib-possibility を削除
・バルクスキャンの定義：Zlib を追加
・決定が適用されたことを確認

他のスライドの新規のコメントがまだありますので、変更は後ほどで結構です。

**Comment by KoukiHama** [comment]
自分自身でも気づくべきでした．ご指摘ありがとうございます．

もう一つのファイルへ
・Zlib-possibility を選択
・バルクスキャンの定義：Zlib-possibility を削除
・バルクスキャンの定義：Zlib を追加
・決定が適用されたことを確認

を採用します．

**Comment by nobuoimada** [comment]
変更を確認したのでcloseします。
