### ISSUE TITLE
Module-D, Slide 12 - Solution

### ISSUE THREAD

**Issue by nobuoimada** [KoukiHama/FOSSologySlides#31]
右側のテキストボックス (解決策) の以下の項目について、

(1) Editing the copyright of a file, edits it also for future uploads

原文の意図が今一つわかりませんが、一つのファイルの著作権を編集する(ファイルそのものではなく検出された著作権情報を)ということと、将来のアップロードのためにも (also) 編集する (＝将来のアップロードで結果が再利用される？) ということでしょうか。

(2) Recovery of deleted copyright statements possible

deletedは、自然に「消えた」のではなく、ユーザが削除した、だと思います。

(3) Table-sheet editing up to come
"up to come" ですが、coming soon のような意味で使っているのでしょうか？確信は持てませんが…

以下の訳を提案します。

・ファイルの著作権の編集 - 将来のアップロードのためにも
・削除した著作権ステートメントを可能な限り復元
・テーブルシート編集も対応予定

**Comment by KoukiHama** [comment]
(1) Editing the copyright of a file, edits it also for future uploads
ファイルの著作権の編集 - 将来のアップロードのためにも

(2) Recovery of deleted copyright statements possible
削除した著作権ステートメントを可能な限り復元

(3) Table-sheet editing up to come
テーブルシート編集も対応予定

をそれぞれ採用

**Comment by KoukiHama** [comment]
"up to come" は come up to としても解釈しにくく，やはりcoming soonのように訳しておくといいかと思います．

**Comment by nobuoimada** [comment]
変更を確認したのでcloseします。
