### ISSUE TITLE
Module-D, Slides 17, 21, 23 - Candidate License Handling

### ISSUE THREAD

**Issue by nobuoimada** [KoukiHama/FOSSologySlides#34]
Candidate License Handlingの訳として、候補ライセンス処理、ライセンス候補の取り扱い、があり不統一です。Candidate License はそのままでもよいかなと思います。

それと、Candidate License の作成の仕方がスライド23の右側に書いてありますが、
Create a candidate license
- Filling out the entry
- Clean the text before
- Go back to the file occurrence
- Select from the candidate license

この手順をどの画面で行うのかがわかりませんでした。管理者権限ありのユーザでログインすると、メニューから新規ライセンス追加の画面に行くことができますが、Candidate License というキーワードは見つかりませんでした。上記手順をどの画面で行えばよいか、ご存知ですか？

**Comment by nobuoimada** [comment]
Candidate License の作成手順を実機で調査しました。
- 新規ライセンスの作成 (non-adminユーザも可能)
    - メニューから Organize, License へと進むと、Advice License画面に遷移
    - その画面の New License ボタンを押す
    - フォームに記入
    - Merge request にチェックを入れると、管理者に Merge request が行く
    - Merge request したかどうかにかかわらず、"User Decision ..." からそのライセンスが見えるようになる (この状態が Candidate License)
- ライセンスの追加 (adminユーザのみ可能)
    - メニューから Admin, License Admin, Candidates と進む
    - Merge request された Candidate License が見える
    - Edit を押すと、"Verify as new license", "Compare with" などができる。

**Comment by nobuoimada** [comment]
上記を踏まえて、slide 23の変更案です。
(1) 左側テキストボックス
1. "clearing" 作業中に新しいライセンステキストを見つける
- そのファイルのライセンスエントリーに、そのライセンステキストを保存することはできる (License Text欄の "Click to Add" から)
- OK. でもこれはそのファイルにのみ有効

(2) 右側テキストボックス
- zlib 1.2.7 ソースがアップロード済み
    - contrib ディレクトリ配下の ada の例をチェック
    - “ada” の例外テキストをレビュー
- Candidate License の作成
    - メニューから Organize, License へと進む
    - New License ボタンを押し、内容を記入
    - 事前にテキストをきれいに (コメント記号の除去など)
    - ファイルビューに戻る
    - User Decision ボタンを押してライセンスを選択
- 管理者の作業
    - Candidate License をチェック
    - マージリクエストの処理

**Comment by KoukiHama** [comment]
以下を採用しますが，［事前にテキストをきれいに］-> [事前にテキストをきれいに**する**]
と少し変更をしておきます．

＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝
(1) 左側テキストボックス

"clearing" 作業中に新しいライセンステキストを見つける
そのファイルのライセンスエントリーに、そのライセンステキストを保存することはできる (License Text欄の "Click to Add" から)
OK. でもこれはそのファイルにのみ有効
＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝
(2) 右側テキストボックス

zlib 1.2.7 ソースがアップロード済み
contrib ディレクトリ配下の ada の例をチェック
“ada” の例外テキストをレビュー
Candidate License の作成
メニューから Organize, License へと進む
New License ボタンを押し、内容を記入
事前にテキストをきれいに (コメント記号の除去など)
ファイルビューに戻る
User Decision ボタンを押してライセンスを選択
管理者の作業
Candidate License をチェック

**Comment by KoukiHama** [comment]
Candidate License Handling

を

Candidate License の取り扱い　に統一しました．

**Comment by KoukiHama** [comment]
同様に

原文がCandidate License のものは，そのままにすることとしました．

したがってSlide22　左側もCandidate Licenseのまま

**Comment by nobuoimada** [comment]
変更を確認したのでcloseします。
