### ISSUE TITLE
Module-D, Slide 18 - Upload and clearing of a component:

### ISSUE THREAD

**Issue by nobuoimada** [KoukiHama/FOSSologySlides#35]
(1)左側のテキストボックスの修正案です。

コンポーネントのアップロードと消去
→ コンポーネントのアップロードと "clearing"

おそらくバルクフレーズ利用
→ バルクフレーズを利用してもよい

(2)右側のテキストボックスの修正案です。

既にスキャンの再利用 (新エージェントで再スキャン可能)
→ スキャンの再利用 (新規エージェントでは再スキャンの可能性あり)

注：上の部分の原文の already は、「(すべてのファイルのハッシュ値を保持しているので) 同一ファイルが再度upされた場合には、ユーザが明示しなくても『自動的に』スキャン結果を再利用する」ということを言っていると思うので、あえて「既に」を入れる必要はないと思います。

**Comment by KoukiHama** [comment]
［コンポーネントのアップロードと "clearing"］
［バルクフレーズを利用してもよい］
［スキャンの再利用 (新規エージェントでは再スキャンの可能性あり)］

をそれぞれ採用します．

**Comment by nobuoimada** [comment]
変更を確認したのでcloseします。
