### ISSUE TITLE
Module-D, Slide 20 - Example

### ISSUE THREAD

**Issue by nobuoimada** [KoukiHama/FOSSologySlides#36]
右側のテキストボックスが、現状では手順がわかりにくいので、以下を提案します。

- zlib 1.2.7 のソースが既にアップされている
    - 前のパートで、いくつかの "clearing" 作業が終わっている

- zlib 1.2.8 ソースをアップロード
    - Select an already uploaded package for reuse ... にチェック
    - Upload to reuse: 欄で、アップロード済の zlib 1.2.7 を選択
    - 他の Reuse オプションは何も選択しない
    - スキャン結果から、再利用されたファイルをレビュー

- zlib 1.2.8 を再びアップロード 
    - 再利用するパッケージを選択 (同上)
    - ... bulk phrases from reused packages にもチェック

- zlib 1.2.8 をもう一度アップロード
    - enhanced reuse (slower) にもチェック

**Comment by KoukiHama** [comment]
- zlib 1.2.7 のソースが既にアップされている

前のパートで、いくつかの "clearing" 作業が終わっている

- zlib 1.2.8 ソースをアップロード

Select an already uploaded package for reuse ... にチェック
Upload to reuse: 欄で、アップロード済の zlib 1.2.7 を選択
他の Reuse オプションは何も選択しない
スキャン結果から、再利用されたファイルをレビュー

- zlib 1.2.8 を再びアップロード

再利用するパッケージを選択 (同上)
... bulk phrases from reused packages にもチェック

- zlib 1.2.8 をもう一度アップロード

enhanced reuse (slower) にもチェック



に置き換えます．

**Comment by nobuoimada** [comment]
変更を確認したのでcloseします。
