### ISSUE TITLE
Module-D, Slides 17, 21, 22 - Custom License Text

### ISSUE THREAD

**Issue by nobuoimada** [KoukiHama/FOSSologySlides#37]
「ライセンステキストのカスタム」は、日本語として少しわかりにくいと思います。
案1：カスタムのライセンステキスト
案2：ユーザ定義のライセンステキスト
案3：ライセンステキストのユーザ定義

**Comment by KoukiHama** [comment]
Slides 17, 21, 22それぞれで

案1：カスタムのライセンステキスト
を採用します．

**Comment by nobuoimada** [comment]
変更を確認したのでcloseします。
