### ISSUE TITLE
Module-D, Slide 22 - Custom License Text

### ISSUE THREAD

**Issue by nobuoimada** [KoukiHama/FOSSologySlides#38]
(1) 左側のテキストボックスの修正案

ライセンスのテキスト置換を追加
→ ライセンスの代替テキストを追加

(2) 右側のテキストボックスのコメント

「1ファイルを選択、オプション：タブを使用して複数のファイルを選択」
ですが、オプションの「タブを使用して複数のファイルを選択」の操作がわかりませんでした。

私からのコメントはひとまずここまでです。たくさんのコメントにお付き合いいただきありがとうございました。

**Comment by KoukiHama** [comment]
今，操作しながらの確認ができないのですが，

［ライセンスの代替テキストを追加］
「1ファイルを選択、オプション：タブを使用して複数のファイルを選択」

をそれぞれ採用します．

**Comment by nobuoimada** [comment]
変更を確認したのでcloseします。
