### ISSUE TITLE
Module-D, Slide 26 - Review work can be tedious

### ISSUE THREAD

**Issue by nobuoimada** [KoukiHama/FOSSologySlides#39]
ひとまずここまでと書きましたが、まだありました。

(1) スキャナーが2つある場合、レビュー作業は面倒です。なぜそれらに仕事をさせないのですか？
修正案：
レビュー作業は退屈。スキャナーが2つあるのだから、それらに仕事をさせよう。

(2) 左側：いくつかのスキャナ、正規表現を持つNomos、テキストを類似させるMonkがある。
修正案：
正規表現によるNomos、テキストの類似性によるMonk、複数のスキャナーがある

(3) 右側：3つ目の Ninka スキャナーも同様に動かす
修正案：
3つめのスキャナーであるNinkaでも同様の効果

**Comment by KoukiHama** [comment]
ひどい誤訳してましたね．

- レビュー作業は退屈。スキャナーが2つあるのだから、それらに仕事をさせよう。

- 正規表現によるNomos、テキストの類似性によるMonk、複数のスキャナーがある

- 3つめのスキャナーであるNinkaでも同様の効果

採用します

**Comment by nobuoimada** [comment]
変更を確認したのでcloseします。
