### ISSUE TITLE
Module-A, Slide 4, Further reading

### ISSUE THREAD

**Issue by nobuoimada** [KoukiHama/FOSSologySlides#4]
スライド右側の Further reading: の訳がないので、私が訳したものを参考までに提案します。

もっと知りたい人は…
・Open Source Automation Development Lab (OSADL) が、さまざまなライセンスの義務条件データを公開しています。https://www.osadl.org/Access-to-raw-data.oss-compliance-raw-data-access.0.html

"Further reading" を「もっと知りたい人は」と訳しましたが、好みの問題もあるので、採否はお任せします。

**Comment by KoukiHama** [comment]
［もっと知りたい人は］
［Open Source Automation Development Lab (OSADL) が、さまざまなライセンスの義務条件データを公開しています。https://www.osadl.org/Access-to-raw-data.oss-compliance-raw-data-access.0.html］
をスライド右側に追記しました

**Comment by nobuoimada** [comment]
変更を確認したのでcloseします。
