### ISSUE TITLE
Module-D, Slide 27 - balloon

### ISSUE THREAD

**Issue by nobuoimada** [KoukiHama/FOSSologySlides#40]
挿絵の吹き出しが、他のスライドからのコピーのままです。(原文も)
Automatic Concluded License Decider based on 
 ... scanners matches if all Nomos findings are within the Monk findings
を選択するのが正しいと思います。

修正案：
 ... scanners matches if all Nomos findings are within the Monk findings を選択

**Comment by KoukiHama** [comment]
吹き出しの中を
修正案：
... scanners matches if all Nomos findings are within the Monk findings を選択

に変更しました．稚拙な訳のレビューをどうもありがとうございました．

**Comment by nobuoimada** [comment]
変更を確認したのでcloseします。
