### ISSUE TITLE
Module-A, Slide 7, Che Guevarra parafernalia

### ISSUE THREAD

**Issue by nobuoimada** [KoukiHama/FOSSologySlides#5]
原文にある Che Guevarra parafernalia ですが、外国の観光地で売っているような、チェ・ゲバラの肖像画をあしらったＴシャツやバッジなどのことを言っているのではないかと推察します(違うかもしれませんが…)。また、以降のスライドに出てくる例も含めて、そのライセンスのどこがどう問題なのかが原文では明記されていません。日本人が日本語でHands-onの講師をすることを考えると、原文にはなくても、そのあたりが補足してあると、より使いやすい資料になるのではないかと考えます。そこで、以下のような案を考えました。

この例では、チェ・ゲバラのグッズを持っている人の使用を禁止すると書いてある
・面白さを狙って (あるいは政治的な主張を) 書かれたものは、ライセンス解析には厄介
・質問：これは無視して良いでしょうか、それとも、著作者はそのようなグッズの所有をチェックするのでしょうか？

原文の the origination の意図がわからないのですが、原著作者という意味に解釈しました。

**Comment by KoukiHama** [comment]
『日本人が日本語でHands-onの講師をすることを考えると、原文にはなくても、そのあたりが補足してあると、より使いやすい資料になるのではないかと考えます。そこで、以下のような案を考えました。』に同意です．

訳は以下を採用しました．
［この例では、チェ・ゲバラのグッズを持っている人の使用を禁止すると書いてある
・面白さを狙って (あるいは政治的な主張を) 書かれたものは、ライセンス解析には厄介
・質問：これは無視して良いでしょうか、それとも、著作者はそのようなグッズの所有をチェックするのでしょうか？］

また
［この例では、チェ・ゲバラのグッズを持っている人の使用を禁止すると書いてある］の部分は訳注であることを記載しました

**Comment by nobuoimada** [comment]
変更を確認したのでcloseします。
